/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CngRouteImport } from './routes/cng'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnergyEcommerceRouteImport } from './routes/energy-ecommerce'
import { Route as EvRouteImport } from './routes/ev'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GetElectricityRouteImport } from './routes/get-electricity'
import { Route as GetFuelRouteImport } from './routes/get-fuel'
import { Route as GreenEnergyRouteImport } from './routes/green-energy'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OurServicesRouteImport } from './routes/our-services'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PayBillsRouteImport } from './routes/pay-bills'
import { Route as PowerAsAServiceRouteImport } from './routes/power-as-a-service'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CngRoute = CngRouteImport.update({
  id: '/cng',
  path: '/cng',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyEcommerceRoute = EnergyEcommerceRouteImport.update({
  id: '/energy-ecommerce',
  path: '/energy-ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const EvRoute = EvRouteImport.update({
  id: '/ev',
  path: '/ev',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GetElectricityRoute = GetElectricityRouteImport.update({
  id: '/get-electricity',
  path: '/get-electricity',
  getParentRoute: () => rootRouteImport,
} as any)
const GetFuelRoute = GetFuelRouteImport.update({
  id: '/get-fuel',
  path: '/get-fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const GreenEnergyRoute = GreenEnergyRouteImport.update({
  id: '/green-energy',
  path: '/green-energy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OurServicesRoute = OurServicesRouteImport.update({
  id: '/our-services',
  path: '/our-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBillsRoute = PayBillsRouteImport.update({
  id: '/pay-bills',
  path: '/pay-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerAsAServiceRoute = PowerAsAServiceRouteImport.update({
  id: '/power-as-a-service',
  path: '/power-as-a-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/cng': typeof CngRoute
  '/contact': typeof ContactRoute
  '/energy-ecommerce': typeof EnergyEcommerceRoute
  '/ev': typeof EvRoute
  '/faq': typeof FaqRoute
  '/get-electricity': typeof GetElectricityRoute
  '/get-fuel': typeof GetFuelRoute
  '/green-energy': typeof GreenEnergyRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/our-services': typeof OurServicesRoute
  '/partners': typeof PartnersRoute
  '/pay-bills': typeof PayBillsRoute
  '/power-as-a-service': typeof PowerAsAServiceRoute
  '/register': typeof RegisterRoute
  '/technology': typeof TechnologyRoute
  '/training': typeof TrainingRoute
  '/account': typeof AuthenticatedAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/cng': typeof CngRoute
  '/contact': typeof ContactRoute
  '/energy-ecommerce': typeof EnergyEcommerceRoute
  '/ev': typeof EvRoute
  '/faq': typeof FaqRoute
  '/get-electricity': typeof GetElectricityRoute
  '/get-fuel': typeof GetFuelRoute
  '/green-energy': typeof GreenEnergyRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/our-services': typeof OurServicesRoute
  '/partners': typeof PartnersRoute
  '/pay-bills': typeof PayBillsRoute
  '/power-as-a-service': typeof PowerAsAServiceRoute
  '/register': typeof RegisterRoute
  '/technology': typeof TechnologyRoute
  '/training': typeof TrainingRoute
  '/account': typeof AuthenticatedAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/cng': typeof CngRoute
  '/contact': typeof ContactRoute
  '/energy-ecommerce': typeof EnergyEcommerceRoute
  '/ev': typeof EvRoute
  '/faq': typeof FaqRoute
  '/get-electricity': typeof GetElectricityRoute
  '/get-fuel': typeof GetFuelRoute
  '/green-energy': typeof GreenEnergyRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/our-services': typeof OurServicesRoute
  '/partners': typeof PartnersRoute
  '/pay-bills': typeof PayBillsRoute
  '/power-as-a-service': typeof PowerAsAServiceRoute
  '/register': typeof RegisterRoute
  '/technology': typeof TechnologyRoute
  '/training': typeof TrainingRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/cng'
    | '/contact'
    | '/energy-ecommerce'
    | '/ev'
    | '/faq'
    | '/get-electricity'
    | '/get-fuel'
    | '/green-energy'
    | '/industries'
    | '/login'
    | '/our-services'
    | '/partners'
    | '/pay-bills'
    | '/power-as-a-service'
    | '/register'
    | '/technology'
    | '/training'
    | '/account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/cng'
    | '/contact'
    | '/energy-ecommerce'
    | '/ev'
    | '/faq'
    | '/get-electricity'
    | '/get-fuel'
    | '/green-energy'
    | '/industries'
    | '/login'
    | '/our-services'
    | '/partners'
    | '/pay-bills'
    | '/power-as-a-service'
    | '/register'
    | '/technology'
    | '/training'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/careers'
    | '/cng'
    | '/contact'
    | '/energy-ecommerce'
    | '/ev'
    | '/faq'
    | '/get-electricity'
    | '/get-fuel'
    | '/green-energy'
    | '/industries'
    | '/login'
    | '/our-services'
    | '/partners'
    | '/pay-bills'
    | '/power-as-a-service'
    | '/register'
    | '/technology'
    | '/training'
    | '/_authenticated/account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CngRoute: typeof CngRoute
  ContactRoute: typeof ContactRoute
  EnergyEcommerceRoute: typeof EnergyEcommerceRoute
  EvRoute: typeof EvRoute
  FaqRoute: typeof FaqRoute
  GetElectricityRoute: typeof GetElectricityRoute
  GetFuelRoute: typeof GetFuelRoute
  GreenEnergyRoute: typeof GreenEnergyRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  OurServicesRoute: typeof OurServicesRoute
  PartnersRoute: typeof PartnersRoute
  PayBillsRoute: typeof PayBillsRoute
  PowerAsAServiceRoute: typeof PowerAsAServiceRoute
  RegisterRoute: typeof RegisterRoute
  TechnologyRoute: typeof TechnologyRoute
  TrainingRoute: typeof TrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cng': {
      id: '/cng'
      path: '/cng'
      fullPath: '/cng'
      preLoaderRoute: typeof CngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-ecommerce': {
      id: '/energy-ecommerce'
      path: '/energy-ecommerce'
      fullPath: '/energy-ecommerce'
      preLoaderRoute: typeof EnergyEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ev': {
      id: '/ev'
      path: '/ev'
      fullPath: '/ev'
      preLoaderRoute: typeof EvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-electricity': {
      id: '/get-electricity'
      path: '/get-electricity'
      fullPath: '/get-electricity'
      preLoaderRoute: typeof GetElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-fuel': {
      id: '/get-fuel'
      path: '/get-fuel'
      fullPath: '/get-fuel'
      preLoaderRoute: typeof GetFuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/green-energy': {
      id: '/green-energy'
      path: '/green-energy'
      fullPath: '/green-energy'
      preLoaderRoute: typeof GreenEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-services': {
      id: '/our-services'
      path: '/our-services'
      fullPath: '/our-services'
      preLoaderRoute: typeof OurServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-bills': {
      id: '/pay-bills'
      path: '/pay-bills'
      fullPath: '/pay-bills'
      preLoaderRoute: typeof PayBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-as-a-service': {
      id: '/power-as-a-service'
      path: '/power-as-a-service'
      fullPath: '/power-as-a-service'
      preLoaderRoute: typeof PowerAsAServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CngRoute: CngRoute,
  ContactRoute: ContactRoute,
  EnergyEcommerceRoute: EnergyEcommerceRoute,
  EvRoute: EvRoute,
  FaqRoute: FaqRoute,
  GetElectricityRoute: GetElectricityRoute,
  GetFuelRoute: GetFuelRoute,
  GreenEnergyRoute: GreenEnergyRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  OurServicesRoute: OurServicesRoute,
  PartnersRoute: PartnersRoute,
  PayBillsRoute: PayBillsRoute,
  PowerAsAServiceRoute: PowerAsAServiceRoute,
  RegisterRoute: RegisterRoute,
  TechnologyRoute: TechnologyRoute,
  TrainingRoute: TrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
