/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CngRouteImport } from './routes/cng'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EeaRouteImport } from './routes/eea'
import { Route as EnergyEcommerceRouteImport } from './routes/energy-ecommerce'
import { Route as EnergySavingEquipmentRouteImport } from './routes/energy-saving-equipment'
import { Route as EnergyTransitionRouteImport } from './routes/energy-transition'
import { Route as EvRouteImport } from './routes/ev'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GetElectricityRouteImport } from './routes/get-electricity'
import { Route as GetFuelRouteImport } from './routes/get-fuel'
import { Route as GreenEnergyRouteImport } from './routes/green-energy'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OurServicesRouteImport } from './routes/our-services'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PayBillsRouteImport } from './routes/pay-bills'
import { Route as PowerAsAServiceRouteImport } from './routes/power-as-a-service'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RequestEnergyQuoteRouteImport } from './routes/request-energy-quote'
import { Route as SmartMeteringRouteImport } from './routes/smart-metering'
import { Route as SolarPowerRouteImport } from './routes/solar-power'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiSophiaRouteImport } from './routes/api/sophia'
import { Route as CompanyAboutRouteImport } from './routes/company/about'
import { Route as CompanyCareersRouteImport } from './routes/company/careers'
import { Route as CompanyContactRouteImport } from './routes/company/contact'
import { Route as CompanyFaqRouteImport } from './routes/company/faq'
import { Route as CompanyGreenEnergyRouteImport } from './routes/company/green-energy'
import { Route as CompanyIndustriesRouteImport } from './routes/company/industries'
import { Route as CompanyPartnersRouteImport } from './routes/company/partners'
import { Route as CompanyTechnologyRouteImport } from './routes/company/technology'
import { Route as PoliciesGenderDiversityInclusionRouteImport } from './routes/policies.gender-diversity-inclusion'
import { Route as SophiaIndexRouteImport } from './routes/sophia.index'
import { Route as SophiaThreadIdRouteImport } from './routes/sophia.$threadId'
import { Route as TrainingCertificationIndexRouteImport } from './routes/training-certification/index'
import { Route as TrainingCertificationCorporateRouteImport } from './routes/training-certification/corporate'
import { Route as TrainingCertificationCpdRouteImport } from './routes/training-certification/cpd'
import { Route as TrainingCertificationVerifyRouteImport } from './routes/training-certification/verify'
import { Route as TrainingCertificationWaitlistRouteImport } from './routes/training-certification/waitlist'
import { Route as CompanySolutionsIndexRouteImport } from './routes/company/solutions/index'
import { Route as CompanySolutionsCngRouteImport } from './routes/company/solutions/cng'
import { Route as CompanySolutionsCngConversionRouteImport } from './routes/company/solutions/cng-conversion'
import { Route as CompanySolutionsDieselRouteImport } from './routes/company/solutions/diesel'
import { Route as CompanySolutionsEeaRouteImport } from './routes/company/solutions/eea'
import { Route as CompanySolutionsElectricityRouteImport } from './routes/company/solutions/electricity'
import { Route as CompanySolutionsEvChargingRouteImport } from './routes/company/solutions/ev-charging'
import { Route as CompanySolutionsEvMobilityRouteImport } from './routes/company/solutions/ev-mobility'
import { Route as CompanySolutionsMiniGridsRouteImport } from './routes/company/solutions/mini-grids'
import { Route as CompanySolutionsPowerAsAServiceRouteImport } from './routes/company/solutions/power-as-a-service'
import { Route as CompanySolutionsRenewablesRouteImport } from './routes/company/solutions/renewables'
import { Route as CompanySolutionsSmartMeteringRouteImport } from './routes/company/solutions/smart-metering'
import { Route as CompanySolutionsTrainingRouteImport } from './routes/company/solutions/training'
import { Route as TrainingCertificationProfessionalCertificationsIndexRouteImport } from './routes/training-certification/professional-certifications/index'
import { Route as TrainingCertificationProfessionalCertificationsCodeRouteImport } from './routes/training-certification/professional-certifications/$code'
import { Route as TrainingCertificationProfessionalCertificationsWaitlistRouteImport } from './routes/training-certification/professional-certifications/waitlist'
import { Route as TrainingCertificationProgrammesSlugRouteImport } from './routes/training-certification/programmes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CngRoute = CngRouteImport.update({
  id: '/cng',
  path: '/cng',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EeaRoute = EeaRouteImport.update({
  id: '/eea',
  path: '/eea',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyEcommerceRoute = EnergyEcommerceRouteImport.update({
  id: '/energy-ecommerce',
  path: '/energy-ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergySavingEquipmentRoute = EnergySavingEquipmentRouteImport.update({
  id: '/energy-saving-equipment',
  path: '/energy-saving-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyTransitionRoute = EnergyTransitionRouteImport.update({
  id: '/energy-transition',
  path: '/energy-transition',
  getParentRoute: () => rootRouteImport,
} as any)
const EvRoute = EvRouteImport.update({
  id: '/ev',
  path: '/ev',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GetElectricityRoute = GetElectricityRouteImport.update({
  id: '/get-electricity',
  path: '/get-electricity',
  getParentRoute: () => rootRouteImport,
} as any)
const GetFuelRoute = GetFuelRouteImport.update({
  id: '/get-fuel',
  path: '/get-fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const GreenEnergyRoute = GreenEnergyRouteImport.update({
  id: '/green-energy',
  path: '/green-energy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OurServicesRoute = OurServicesRouteImport.update({
  id: '/our-services',
  path: '/our-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBillsRoute = PayBillsRouteImport.update({
  id: '/pay-bills',
  path: '/pay-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerAsAServiceRoute = PowerAsAServiceRouteImport.update({
  id: '/power-as-a-service',
  path: '/power-as-a-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestEnergyQuoteRoute = RequestEnergyQuoteRouteImport.update({
  id: '/request-energy-quote',
  path: '/request-energy-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartMeteringRoute = SmartMeteringRouteImport.update({
  id: '/smart-metering',
  path: '/smart-metering',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarPowerRoute = SolarPowerRouteImport.update({
  id: '/solar-power',
  path: '/solar-power',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSophiaRoute = ApiSophiaRouteImport.update({
  id: '/api/sophia',
  path: '/api/sophia',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAboutRoute = CompanyAboutRouteImport.update({
  id: '/company/about',
  path: '/company/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCareersRoute = CompanyCareersRouteImport.update({
  id: '/company/careers',
  path: '/company/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyContactRoute = CompanyContactRouteImport.update({
  id: '/company/contact',
  path: '/company/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyFaqRoute = CompanyFaqRouteImport.update({
  id: '/company/faq',
  path: '/company/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyGreenEnergyRoute = CompanyGreenEnergyRouteImport.update({
  id: '/company/green-energy',
  path: '/company/green-energy',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndustriesRoute = CompanyIndustriesRouteImport.update({
  id: '/company/industries',
  path: '/company/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPartnersRoute = CompanyPartnersRouteImport.update({
  id: '/company/partners',
  path: '/company/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyTechnologyRoute = CompanyTechnologyRouteImport.update({
  id: '/company/technology',
  path: '/company/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesGenderDiversityInclusionRoute =
  PoliciesGenderDiversityInclusionRouteImport.update({
    id: '/policies/gender-diversity-inclusion',
    path: '/policies/gender-diversity-inclusion',
    getParentRoute: () => rootRouteImport,
  } as any)
const SophiaIndexRoute = SophiaIndexRouteImport.update({
  id: '/sophia/',
  path: '/sophia/',
  getParentRoute: () => rootRouteImport,
} as any)
const SophiaThreadIdRoute = SophiaThreadIdRouteImport.update({
  id: '/sophia/$threadId',
  path: '/sophia/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingCertificationIndexRoute =
  TrainingCertificationIndexRouteImport.update({
    id: '/training-certification/',
    path: '/training-certification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrainingCertificationCorporateRoute =
  TrainingCertificationCorporateRouteImport.update({
    id: '/training-certification/corporate',
    path: '/training-certification/corporate',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrainingCertificationCpdRoute =
  TrainingCertificationCpdRouteImport.update({
    id: '/training-certification/cpd',
    path: '/training-certification/cpd',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrainingCertificationVerifyRoute =
  TrainingCertificationVerifyRouteImport.update({
    id: '/training-certification/verify',
    path: '/training-certification/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrainingCertificationWaitlistRoute =
  TrainingCertificationWaitlistRouteImport.update({
    id: '/training-certification/waitlist',
    path: '/training-certification/waitlist',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanySolutionsIndexRoute = CompanySolutionsIndexRouteImport.update({
  id: '/company/solutions/',
  path: '/company/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySolutionsCngRoute = CompanySolutionsCngRouteImport.update({
  id: '/company/solutions/cng',
  path: '/company/solutions/cng',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySolutionsCngConversionRoute =
  CompanySolutionsCngConversionRouteImport.update({
    id: '/company/solutions/cng-conversion',
    path: '/company/solutions/cng-conversion',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanySolutionsDieselRoute = CompanySolutionsDieselRouteImport.update({
  id: '/company/solutions/diesel',
  path: '/company/solutions/diesel',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySolutionsEeaRoute = CompanySolutionsEeaRouteImport.update({
  id: '/company/solutions/eea',
  path: '/company/solutions/eea',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySolutionsElectricityRoute =
  CompanySolutionsElectricityRouteImport.update({
    id: '/company/solutions/electricity',
    path: '/company/solutions/electricity',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanySolutionsEvChargingRoute =
  CompanySolutionsEvChargingRouteImport.update({
    id: '/company/solutions/ev-charging',
    path: '/company/solutions/ev-charging',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanySolutionsEvMobilityRoute =
  CompanySolutionsEvMobilityRouteImport.update({
    id: '/company/solutions/ev-mobility',
    path: '/company/solutions/ev-mobility',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanySolutionsMiniGridsRoute =
  CompanySolutionsMiniGridsRouteImport.update({
    id: '/company/solutions/mini-grids',
    path: '/company/solutions/mini-grids',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanySolutionsPowerAsAServiceRoute =
  CompanySolutionsPowerAsAServiceRouteImport.update({
    id: '/company/solutions/power-as-a-service',
    path: '/company/solutions/power-as-a-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanySolutionsRenewablesRoute =
  CompanySolutionsRenewablesRouteImport.update({
    id: '/company/solutions/renewables',
    path: '/company/solutions/renewables',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanySolutionsSmartMeteringRoute =
  CompanySolutionsSmartMeteringRouteImport.update({
    id: '/company/solutions/smart-metering',
    path: '/company/solutions/smart-metering',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanySolutionsTrainingRoute =
  CompanySolutionsTrainingRouteImport.update({
    id: '/company/solutions/training',
    path: '/company/solutions/training',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrainingCertificationProfessionalCertificationsIndexRoute =
  TrainingCertificationProfessionalCertificationsIndexRouteImport.update({
    id: '/training-certification/professional-certifications/',
    path: '/training-certification/professional-certifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrainingCertificationProfessionalCertificationsCodeRoute =
  TrainingCertificationProfessionalCertificationsCodeRouteImport.update({
    id: '/training-certification/professional-certifications/$code',
    path: '/training-certification/professional-certifications/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrainingCertificationProfessionalCertificationsWaitlistRoute =
  TrainingCertificationProfessionalCertificationsWaitlistRouteImport.update({
    id: '/training-certification/professional-certifications/waitlist',
    path: '/training-certification/professional-certifications/waitlist',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrainingCertificationProgrammesSlugRoute =
  TrainingCertificationProgrammesSlugRouteImport.update({
    id: '/training-certification/programmes/$slug',
    path: '/training-certification/programmes/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/cng': typeof CngRoute
  '/contact': typeof ContactRoute
  '/eea': typeof EeaRoute
  '/energy-ecommerce': typeof EnergyEcommerceRoute
  '/energy-saving-equipment': typeof EnergySavingEquipmentRoute
  '/energy-transition': typeof EnergyTransitionRoute
  '/ev': typeof EvRoute
  '/faq': typeof FaqRoute
  '/get-electricity': typeof GetElectricityRoute
  '/get-fuel': typeof GetFuelRoute
  '/green-energy': typeof GreenEnergyRoute
  '/industries': typeof IndustriesRoute
  '/invest': typeof InvestRoute
  '/login': typeof LoginRoute
  '/our-services': typeof OurServicesRoute
  '/partners': typeof PartnersRoute
  '/pay-bills': typeof PayBillsRoute
  '/power-as-a-service': typeof PowerAsAServiceRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/request-energy-quote': typeof RequestEnergyQuoteRoute
  '/smart-metering': typeof SmartMeteringRoute
  '/solar-power': typeof SolarPowerRoute
  '/technology': typeof TechnologyRoute
  '/training': typeof TrainingRoute
  '/account': typeof AuthenticatedAccountRoute
  '/api/sophia': typeof ApiSophiaRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/faq': typeof CompanyFaqRoute
  '/company/green-energy': typeof CompanyGreenEnergyRoute
  '/company/industries': typeof CompanyIndustriesRoute
  '/company/partners': typeof CompanyPartnersRoute
  '/company/technology': typeof CompanyTechnologyRoute
  '/policies/gender-diversity-inclusion': typeof PoliciesGenderDiversityInclusionRoute
  '/sophia/$threadId': typeof SophiaThreadIdRoute
  '/training-certification/corporate': typeof TrainingCertificationCorporateRoute
  '/training-certification/cpd': typeof TrainingCertificationCpdRoute
  '/training-certification/verify': typeof TrainingCertificationVerifyRoute
  '/training-certification/waitlist': typeof TrainingCertificationWaitlistRoute
  '/sophia/': typeof SophiaIndexRoute
  '/training-certification/': typeof TrainingCertificationIndexRoute
  '/company/solutions/cng': typeof CompanySolutionsCngRoute
  '/company/solutions/cng-conversion': typeof CompanySolutionsCngConversionRoute
  '/company/solutions/diesel': typeof CompanySolutionsDieselRoute
  '/company/solutions/eea': typeof CompanySolutionsEeaRoute
  '/company/solutions/electricity': typeof CompanySolutionsElectricityRoute
  '/company/solutions/ev-charging': typeof CompanySolutionsEvChargingRoute
  '/company/solutions/ev-mobility': typeof CompanySolutionsEvMobilityRoute
  '/company/solutions/mini-grids': typeof CompanySolutionsMiniGridsRoute
  '/company/solutions/power-as-a-service': typeof CompanySolutionsPowerAsAServiceRoute
  '/company/solutions/renewables': typeof CompanySolutionsRenewablesRoute
  '/company/solutions/smart-metering': typeof CompanySolutionsSmartMeteringRoute
  '/company/solutions/training': typeof CompanySolutionsTrainingRoute
  '/training-certification/professional-certifications/$code': typeof TrainingCertificationProfessionalCertificationsCodeRoute
  '/training-certification/professional-certifications/waitlist': typeof TrainingCertificationProfessionalCertificationsWaitlistRoute
  '/training-certification/programmes/$slug': typeof TrainingCertificationProgrammesSlugRoute
  '/company/solutions/': typeof CompanySolutionsIndexRoute
  '/training-certification/professional-certifications/': typeof TrainingCertificationProfessionalCertificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/cng': typeof CngRoute
  '/contact': typeof ContactRoute
  '/eea': typeof EeaRoute
  '/energy-ecommerce': typeof EnergyEcommerceRoute
  '/energy-saving-equipment': typeof EnergySavingEquipmentRoute
  '/energy-transition': typeof EnergyTransitionRoute
  '/ev': typeof EvRoute
  '/faq': typeof FaqRoute
  '/get-electricity': typeof GetElectricityRoute
  '/get-fuel': typeof GetFuelRoute
  '/green-energy': typeof GreenEnergyRoute
  '/industries': typeof IndustriesRoute
  '/invest': typeof InvestRoute
  '/login': typeof LoginRoute
  '/our-services': typeof OurServicesRoute
  '/partners': typeof PartnersRoute
  '/pay-bills': typeof PayBillsRoute
  '/power-as-a-service': typeof PowerAsAServiceRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/request-energy-quote': typeof RequestEnergyQuoteRoute
  '/smart-metering': typeof SmartMeteringRoute
  '/solar-power': typeof SolarPowerRoute
  '/technology': typeof TechnologyRoute
  '/training': typeof TrainingRoute
  '/account': typeof AuthenticatedAccountRoute
  '/api/sophia': typeof ApiSophiaRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/faq': typeof CompanyFaqRoute
  '/company/green-energy': typeof CompanyGreenEnergyRoute
  '/company/industries': typeof CompanyIndustriesRoute
  '/company/partners': typeof CompanyPartnersRoute
  '/company/technology': typeof CompanyTechnologyRoute
  '/policies/gender-diversity-inclusion': typeof PoliciesGenderDiversityInclusionRoute
  '/sophia/$threadId': typeof SophiaThreadIdRoute
  '/training-certification/corporate': typeof TrainingCertificationCorporateRoute
  '/training-certification/cpd': typeof TrainingCertificationCpdRoute
  '/training-certification/verify': typeof TrainingCertificationVerifyRoute
  '/training-certification/waitlist': typeof TrainingCertificationWaitlistRoute
  '/sophia': typeof SophiaIndexRoute
  '/training-certification': typeof TrainingCertificationIndexRoute
  '/company/solutions/cng': typeof CompanySolutionsCngRoute
  '/company/solutions/cng-conversion': typeof CompanySolutionsCngConversionRoute
  '/company/solutions/diesel': typeof CompanySolutionsDieselRoute
  '/company/solutions/eea': typeof CompanySolutionsEeaRoute
  '/company/solutions/electricity': typeof CompanySolutionsElectricityRoute
  '/company/solutions/ev-charging': typeof CompanySolutionsEvChargingRoute
  '/company/solutions/ev-mobility': typeof CompanySolutionsEvMobilityRoute
  '/company/solutions/mini-grids': typeof CompanySolutionsMiniGridsRoute
  '/company/solutions/power-as-a-service': typeof CompanySolutionsPowerAsAServiceRoute
  '/company/solutions/renewables': typeof CompanySolutionsRenewablesRoute
  '/company/solutions/smart-metering': typeof CompanySolutionsSmartMeteringRoute
  '/company/solutions/training': typeof CompanySolutionsTrainingRoute
  '/training-certification/professional-certifications/$code': typeof TrainingCertificationProfessionalCertificationsCodeRoute
  '/training-certification/professional-certifications/waitlist': typeof TrainingCertificationProfessionalCertificationsWaitlistRoute
  '/training-certification/programmes/$slug': typeof TrainingCertificationProgrammesSlugRoute
  '/company/solutions': typeof CompanySolutionsIndexRoute
  '/training-certification/professional-certifications': typeof TrainingCertificationProfessionalCertificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/cng': typeof CngRoute
  '/contact': typeof ContactRoute
  '/eea': typeof EeaRoute
  '/energy-ecommerce': typeof EnergyEcommerceRoute
  '/energy-saving-equipment': typeof EnergySavingEquipmentRoute
  '/energy-transition': typeof EnergyTransitionRoute
  '/ev': typeof EvRoute
  '/faq': typeof FaqRoute
  '/get-electricity': typeof GetElectricityRoute
  '/get-fuel': typeof GetFuelRoute
  '/green-energy': typeof GreenEnergyRoute
  '/industries': typeof IndustriesRoute
  '/invest': typeof InvestRoute
  '/login': typeof LoginRoute
  '/our-services': typeof OurServicesRoute
  '/partners': typeof PartnersRoute
  '/pay-bills': typeof PayBillsRoute
  '/power-as-a-service': typeof PowerAsAServiceRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/request-energy-quote': typeof RequestEnergyQuoteRoute
  '/smart-metering': typeof SmartMeteringRoute
  '/solar-power': typeof SolarPowerRoute
  '/technology': typeof TechnologyRoute
  '/training': typeof TrainingRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/api/sophia': typeof ApiSophiaRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/contact': typeof CompanyContactRoute
  '/company/faq': typeof CompanyFaqRoute
  '/company/green-energy': typeof CompanyGreenEnergyRoute
  '/company/industries': typeof CompanyIndustriesRoute
  '/company/partners': typeof CompanyPartnersRoute
  '/company/technology': typeof CompanyTechnologyRoute
  '/policies/gender-diversity-inclusion': typeof PoliciesGenderDiversityInclusionRoute
  '/sophia/$threadId': typeof SophiaThreadIdRoute
  '/training-certification/corporate': typeof TrainingCertificationCorporateRoute
  '/training-certification/cpd': typeof TrainingCertificationCpdRoute
  '/training-certification/verify': typeof TrainingCertificationVerifyRoute
  '/training-certification/waitlist': typeof TrainingCertificationWaitlistRoute
  '/sophia/': typeof SophiaIndexRoute
  '/training-certification/': typeof TrainingCertificationIndexRoute
  '/company/solutions/cng': typeof CompanySolutionsCngRoute
  '/company/solutions/cng-conversion': typeof CompanySolutionsCngConversionRoute
  '/company/solutions/diesel': typeof CompanySolutionsDieselRoute
  '/company/solutions/eea': typeof CompanySolutionsEeaRoute
  '/company/solutions/electricity': typeof CompanySolutionsElectricityRoute
  '/company/solutions/ev-charging': typeof CompanySolutionsEvChargingRoute
  '/company/solutions/ev-mobility': typeof CompanySolutionsEvMobilityRoute
  '/company/solutions/mini-grids': typeof CompanySolutionsMiniGridsRoute
  '/company/solutions/power-as-a-service': typeof CompanySolutionsPowerAsAServiceRoute
  '/company/solutions/renewables': typeof CompanySolutionsRenewablesRoute
  '/company/solutions/smart-metering': typeof CompanySolutionsSmartMeteringRoute
  '/company/solutions/training': typeof CompanySolutionsTrainingRoute
  '/training-certification/professional-certifications/$code': typeof TrainingCertificationProfessionalCertificationsCodeRoute
  '/training-certification/professional-certifications/waitlist': typeof TrainingCertificationProfessionalCertificationsWaitlistRoute
  '/training-certification/programmes/$slug': typeof TrainingCertificationProgrammesSlugRoute
  '/company/solutions/': typeof CompanySolutionsIndexRoute
  '/training-certification/professional-certifications/': typeof TrainingCertificationProfessionalCertificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/cng'
    | '/contact'
    | '/eea'
    | '/energy-ecommerce'
    | '/energy-saving-equipment'
    | '/energy-transition'
    | '/ev'
    | '/faq'
    | '/get-electricity'
    | '/get-fuel'
    | '/green-energy'
    | '/industries'
    | '/invest'
    | '/login'
    | '/our-services'
    | '/partners'
    | '/pay-bills'
    | '/power-as-a-service'
    | '/projects'
    | '/register'
    | '/request-energy-quote'
    | '/smart-metering'
    | '/solar-power'
    | '/technology'
    | '/training'
    | '/account'
    | '/api/sophia'
    | '/company/about'
    | '/company/careers'
    | '/company/contact'
    | '/company/faq'
    | '/company/green-energy'
    | '/company/industries'
    | '/company/partners'
    | '/company/technology'
    | '/policies/gender-diversity-inclusion'
    | '/sophia/$threadId'
    | '/training-certification/corporate'
    | '/training-certification/cpd'
    | '/training-certification/verify'
    | '/training-certification/waitlist'
    | '/sophia/'
    | '/training-certification/'
    | '/company/solutions/cng'
    | '/company/solutions/cng-conversion'
    | '/company/solutions/diesel'
    | '/company/solutions/eea'
    | '/company/solutions/electricity'
    | '/company/solutions/ev-charging'
    | '/company/solutions/ev-mobility'
    | '/company/solutions/mini-grids'
    | '/company/solutions/power-as-a-service'
    | '/company/solutions/renewables'
    | '/company/solutions/smart-metering'
    | '/company/solutions/training'
    | '/training-certification/professional-certifications/$code'
    | '/training-certification/professional-certifications/waitlist'
    | '/training-certification/programmes/$slug'
    | '/company/solutions/'
    | '/training-certification/professional-certifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/cng'
    | '/contact'
    | '/eea'
    | '/energy-ecommerce'
    | '/energy-saving-equipment'
    | '/energy-transition'
    | '/ev'
    | '/faq'
    | '/get-electricity'
    | '/get-fuel'
    | '/green-energy'
    | '/industries'
    | '/invest'
    | '/login'
    | '/our-services'
    | '/partners'
    | '/pay-bills'
    | '/power-as-a-service'
    | '/projects'
    | '/register'
    | '/request-energy-quote'
    | '/smart-metering'
    | '/solar-power'
    | '/technology'
    | '/training'
    | '/account'
    | '/api/sophia'
    | '/company/about'
    | '/company/careers'
    | '/company/contact'
    | '/company/faq'
    | '/company/green-energy'
    | '/company/industries'
    | '/company/partners'
    | '/company/technology'
    | '/policies/gender-diversity-inclusion'
    | '/sophia/$threadId'
    | '/training-certification/corporate'
    | '/training-certification/cpd'
    | '/training-certification/verify'
    | '/training-certification/waitlist'
    | '/sophia'
    | '/training-certification'
    | '/company/solutions/cng'
    | '/company/solutions/cng-conversion'
    | '/company/solutions/diesel'
    | '/company/solutions/eea'
    | '/company/solutions/electricity'
    | '/company/solutions/ev-charging'
    | '/company/solutions/ev-mobility'
    | '/company/solutions/mini-grids'
    | '/company/solutions/power-as-a-service'
    | '/company/solutions/renewables'
    | '/company/solutions/smart-metering'
    | '/company/solutions/training'
    | '/training-certification/professional-certifications/$code'
    | '/training-certification/professional-certifications/waitlist'
    | '/training-certification/programmes/$slug'
    | '/company/solutions'
    | '/training-certification/professional-certifications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/careers'
    | '/cng'
    | '/contact'
    | '/eea'
    | '/energy-ecommerce'
    | '/energy-saving-equipment'
    | '/energy-transition'
    | '/ev'
    | '/faq'
    | '/get-electricity'
    | '/get-fuel'
    | '/green-energy'
    | '/industries'
    | '/invest'
    | '/login'
    | '/our-services'
    | '/partners'
    | '/pay-bills'
    | '/power-as-a-service'
    | '/projects'
    | '/register'
    | '/request-energy-quote'
    | '/smart-metering'
    | '/solar-power'
    | '/technology'
    | '/training'
    | '/_authenticated/account'
    | '/api/sophia'
    | '/company/about'
    | '/company/careers'
    | '/company/contact'
    | '/company/faq'
    | '/company/green-energy'
    | '/company/industries'
    | '/company/partners'
    | '/company/technology'
    | '/policies/gender-diversity-inclusion'
    | '/sophia/$threadId'
    | '/training-certification/corporate'
    | '/training-certification/cpd'
    | '/training-certification/verify'
    | '/training-certification/waitlist'
    | '/sophia/'
    | '/training-certification/'
    | '/company/solutions/cng'
    | '/company/solutions/cng-conversion'
    | '/company/solutions/diesel'
    | '/company/solutions/eea'
    | '/company/solutions/electricity'
    | '/company/solutions/ev-charging'
    | '/company/solutions/ev-mobility'
    | '/company/solutions/mini-grids'
    | '/company/solutions/power-as-a-service'
    | '/company/solutions/renewables'
    | '/company/solutions/smart-metering'
    | '/company/solutions/training'
    | '/training-certification/professional-certifications/$code'
    | '/training-certification/professional-certifications/waitlist'
    | '/training-certification/programmes/$slug'
    | '/company/solutions/'
    | '/training-certification/professional-certifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CngRoute: typeof CngRoute
  ContactRoute: typeof ContactRoute
  EeaRoute: typeof EeaRoute
  EnergyEcommerceRoute: typeof EnergyEcommerceRoute
  EnergySavingEquipmentRoute: typeof EnergySavingEquipmentRoute
  EnergyTransitionRoute: typeof EnergyTransitionRoute
  EvRoute: typeof EvRoute
  FaqRoute: typeof FaqRoute
  GetElectricityRoute: typeof GetElectricityRoute
  GetFuelRoute: typeof GetFuelRoute
  GreenEnergyRoute: typeof GreenEnergyRoute
  IndustriesRoute: typeof IndustriesRoute
  InvestRoute: typeof InvestRoute
  LoginRoute: typeof LoginRoute
  OurServicesRoute: typeof OurServicesRoute
  PartnersRoute: typeof PartnersRoute
  PayBillsRoute: typeof PayBillsRoute
  PowerAsAServiceRoute: typeof PowerAsAServiceRoute
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  RequestEnergyQuoteRoute: typeof RequestEnergyQuoteRoute
  SmartMeteringRoute: typeof SmartMeteringRoute
  SolarPowerRoute: typeof SolarPowerRoute
  TechnologyRoute: typeof TechnologyRoute
  TrainingRoute: typeof TrainingRoute
  ApiSophiaRoute: typeof ApiSophiaRoute
  CompanyAboutRoute: typeof CompanyAboutRoute
  CompanyCareersRoute: typeof CompanyCareersRoute
  CompanyContactRoute: typeof CompanyContactRoute
  CompanyFaqRoute: typeof CompanyFaqRoute
  CompanyGreenEnergyRoute: typeof CompanyGreenEnergyRoute
  CompanyIndustriesRoute: typeof CompanyIndustriesRoute
  CompanyPartnersRoute: typeof CompanyPartnersRoute
  CompanyTechnologyRoute: typeof CompanyTechnologyRoute
  PoliciesGenderDiversityInclusionRoute: typeof PoliciesGenderDiversityInclusionRoute
  SophiaThreadIdRoute: typeof SophiaThreadIdRoute
  TrainingCertificationCorporateRoute: typeof TrainingCertificationCorporateRoute
  TrainingCertificationCpdRoute: typeof TrainingCertificationCpdRoute
  TrainingCertificationVerifyRoute: typeof TrainingCertificationVerifyRoute
  TrainingCertificationWaitlistRoute: typeof TrainingCertificationWaitlistRoute
  SophiaIndexRoute: typeof SophiaIndexRoute
  TrainingCertificationIndexRoute: typeof TrainingCertificationIndexRoute
  CompanySolutionsCngRoute: typeof CompanySolutionsCngRoute
  CompanySolutionsCngConversionRoute: typeof CompanySolutionsCngConversionRoute
  CompanySolutionsDieselRoute: typeof CompanySolutionsDieselRoute
  CompanySolutionsEeaRoute: typeof CompanySolutionsEeaRoute
  CompanySolutionsElectricityRoute: typeof CompanySolutionsElectricityRoute
  CompanySolutionsEvChargingRoute: typeof CompanySolutionsEvChargingRoute
  CompanySolutionsEvMobilityRoute: typeof CompanySolutionsEvMobilityRoute
  CompanySolutionsMiniGridsRoute: typeof CompanySolutionsMiniGridsRoute
  CompanySolutionsPowerAsAServiceRoute: typeof CompanySolutionsPowerAsAServiceRoute
  CompanySolutionsRenewablesRoute: typeof CompanySolutionsRenewablesRoute
  CompanySolutionsSmartMeteringRoute: typeof CompanySolutionsSmartMeteringRoute
  CompanySolutionsTrainingRoute: typeof CompanySolutionsTrainingRoute
  TrainingCertificationProfessionalCertificationsCodeRoute: typeof TrainingCertificationProfessionalCertificationsCodeRoute
  TrainingCertificationProfessionalCertificationsWaitlistRoute: typeof TrainingCertificationProfessionalCertificationsWaitlistRoute
  TrainingCertificationProgrammesSlugRoute: typeof TrainingCertificationProgrammesSlugRoute
  CompanySolutionsIndexRoute: typeof CompanySolutionsIndexRoute
  TrainingCertificationProfessionalCertificationsIndexRoute: typeof TrainingCertificationProfessionalCertificationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cng': {
      id: '/cng'
      path: '/cng'
      fullPath: '/cng'
      preLoaderRoute: typeof CngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eea': {
      id: '/eea'
      path: '/eea'
      fullPath: '/eea'
      preLoaderRoute: typeof EeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-ecommerce': {
      id: '/energy-ecommerce'
      path: '/energy-ecommerce'
      fullPath: '/energy-ecommerce'
      preLoaderRoute: typeof EnergyEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-saving-equipment': {
      id: '/energy-saving-equipment'
      path: '/energy-saving-equipment'
      fullPath: '/energy-saving-equipment'
      preLoaderRoute: typeof EnergySavingEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-transition': {
      id: '/energy-transition'
      path: '/energy-transition'
      fullPath: '/energy-transition'
      preLoaderRoute: typeof EnergyTransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ev': {
      id: '/ev'
      path: '/ev'
      fullPath: '/ev'
      preLoaderRoute: typeof EvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-electricity': {
      id: '/get-electricity'
      path: '/get-electricity'
      fullPath: '/get-electricity'
      preLoaderRoute: typeof GetElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-fuel': {
      id: '/get-fuel'
      path: '/get-fuel'
      fullPath: '/get-fuel'
      preLoaderRoute: typeof GetFuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/green-energy': {
      id: '/green-energy'
      path: '/green-energy'
      fullPath: '/green-energy'
      preLoaderRoute: typeof GreenEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-services': {
      id: '/our-services'
      path: '/our-services'
      fullPath: '/our-services'
      preLoaderRoute: typeof OurServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-bills': {
      id: '/pay-bills'
      path: '/pay-bills'
      fullPath: '/pay-bills'
      preLoaderRoute: typeof PayBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-as-a-service': {
      id: '/power-as-a-service'
      path: '/power-as-a-service'
      fullPath: '/power-as-a-service'
      preLoaderRoute: typeof PowerAsAServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-energy-quote': {
      id: '/request-energy-quote'
      path: '/request-energy-quote'
      fullPath: '/request-energy-quote'
      preLoaderRoute: typeof RequestEnergyQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-metering': {
      id: '/smart-metering'
      path: '/smart-metering'
      fullPath: '/smart-metering'
      preLoaderRoute: typeof SmartMeteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-power': {
      id: '/solar-power'
      path: '/solar-power'
      fullPath: '/solar-power'
      preLoaderRoute: typeof SolarPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/sophia': {
      id: '/api/sophia'
      path: '/api/sophia'
      fullPath: '/api/sophia'
      preLoaderRoute: typeof ApiSophiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/about': {
      id: '/company/about'
      path: '/company/about'
      fullPath: '/company/about'
      preLoaderRoute: typeof CompanyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/careers': {
      id: '/company/careers'
      path: '/company/careers'
      fullPath: '/company/careers'
      preLoaderRoute: typeof CompanyCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/contact': {
      id: '/company/contact'
      path: '/company/contact'
      fullPath: '/company/contact'
      preLoaderRoute: typeof CompanyContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/faq': {
      id: '/company/faq'
      path: '/company/faq'
      fullPath: '/company/faq'
      preLoaderRoute: typeof CompanyFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/green-energy': {
      id: '/company/green-energy'
      path: '/company/green-energy'
      fullPath: '/company/green-energy'
      preLoaderRoute: typeof CompanyGreenEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/industries': {
      id: '/company/industries'
      path: '/company/industries'
      fullPath: '/company/industries'
      preLoaderRoute: typeof CompanyIndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/partners': {
      id: '/company/partners'
      path: '/company/partners'
      fullPath: '/company/partners'
      preLoaderRoute: typeof CompanyPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/technology': {
      id: '/company/technology'
      path: '/company/technology'
      fullPath: '/company/technology'
      preLoaderRoute: typeof CompanyTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/gender-diversity-inclusion': {
      id: '/policies/gender-diversity-inclusion'
      path: '/policies/gender-diversity-inclusion'
      fullPath: '/policies/gender-diversity-inclusion'
      preLoaderRoute: typeof PoliciesGenderDiversityInclusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sophia/': {
      id: '/sophia/'
      path: '/sophia'
      fullPath: '/sophia/'
      preLoaderRoute: typeof SophiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sophia/$threadId': {
      id: '/sophia/$threadId'
      path: '/sophia/$threadId'
      fullPath: '/sophia/$threadId'
      preLoaderRoute: typeof SophiaThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-certification/': {
      id: '/training-certification/'
      path: '/training-certification'
      fullPath: '/training-certification/'
      preLoaderRoute: typeof TrainingCertificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-certification/corporate': {
      id: '/training-certification/corporate'
      path: '/training-certification/corporate'
      fullPath: '/training-certification/corporate'
      preLoaderRoute: typeof TrainingCertificationCorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-certification/cpd': {
      id: '/training-certification/cpd'
      path: '/training-certification/cpd'
      fullPath: '/training-certification/cpd'
      preLoaderRoute: typeof TrainingCertificationCpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-certification/verify': {
      id: '/training-certification/verify'
      path: '/training-certification/verify'
      fullPath: '/training-certification/verify'
      preLoaderRoute: typeof TrainingCertificationVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-certification/waitlist': {
      id: '/training-certification/waitlist'
      path: '/training-certification/waitlist'
      fullPath: '/training-certification/waitlist'
      preLoaderRoute: typeof TrainingCertificationWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/': {
      id: '/company/solutions/'
      path: '/company/solutions'
      fullPath: '/company/solutions/'
      preLoaderRoute: typeof CompanySolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/cng': {
      id: '/company/solutions/cng'
      path: '/company/solutions/cng'
      fullPath: '/company/solutions/cng'
      preLoaderRoute: typeof CompanySolutionsCngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/cng-conversion': {
      id: '/company/solutions/cng-conversion'
      path: '/company/solutions/cng-conversion'
      fullPath: '/company/solutions/cng-conversion'
      preLoaderRoute: typeof CompanySolutionsCngConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/diesel': {
      id: '/company/solutions/diesel'
      path: '/company/solutions/diesel'
      fullPath: '/company/solutions/diesel'
      preLoaderRoute: typeof CompanySolutionsDieselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/eea': {
      id: '/company/solutions/eea'
      path: '/company/solutions/eea'
      fullPath: '/company/solutions/eea'
      preLoaderRoute: typeof CompanySolutionsEeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/electricity': {
      id: '/company/solutions/electricity'
      path: '/company/solutions/electricity'
      fullPath: '/company/solutions/electricity'
      preLoaderRoute: typeof CompanySolutionsElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/ev-charging': {
      id: '/company/solutions/ev-charging'
      path: '/company/solutions/ev-charging'
      fullPath: '/company/solutions/ev-charging'
      preLoaderRoute: typeof CompanySolutionsEvChargingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/ev-mobility': {
      id: '/company/solutions/ev-mobility'
      path: '/company/solutions/ev-mobility'
      fullPath: '/company/solutions/ev-mobility'
      preLoaderRoute: typeof CompanySolutionsEvMobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/mini-grids': {
      id: '/company/solutions/mini-grids'
      path: '/company/solutions/mini-grids'
      fullPath: '/company/solutions/mini-grids'
      preLoaderRoute: typeof CompanySolutionsMiniGridsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/power-as-a-service': {
      id: '/company/solutions/power-as-a-service'
      path: '/company/solutions/power-as-a-service'
      fullPath: '/company/solutions/power-as-a-service'
      preLoaderRoute: typeof CompanySolutionsPowerAsAServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/renewables': {
      id: '/company/solutions/renewables'
      path: '/company/solutions/renewables'
      fullPath: '/company/solutions/renewables'
      preLoaderRoute: typeof CompanySolutionsRenewablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/smart-metering': {
      id: '/company/solutions/smart-metering'
      path: '/company/solutions/smart-metering'
      fullPath: '/company/solutions/smart-metering'
      preLoaderRoute: typeof CompanySolutionsSmartMeteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/solutions/training': {
      id: '/company/solutions/training'
      path: '/company/solutions/training'
      fullPath: '/company/solutions/training'
      preLoaderRoute: typeof CompanySolutionsTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-certification/professional-certifications/': {
      id: '/training-certification/professional-certifications/'
      path: '/training-certification/professional-certifications'
      fullPath: '/training-certification/professional-certifications/'
      preLoaderRoute: typeof TrainingCertificationProfessionalCertificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-certification/professional-certifications/$code': {
      id: '/training-certification/professional-certifications/$code'
      path: '/training-certification/professional-certifications/$code'
      fullPath: '/training-certification/professional-certifications/$code'
      preLoaderRoute: typeof TrainingCertificationProfessionalCertificationsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-certification/professional-certifications/waitlist': {
      id: '/training-certification/professional-certifications/waitlist'
      path: '/training-certification/professional-certifications/waitlist'
      fullPath: '/training-certification/professional-certifications/waitlist'
      preLoaderRoute: typeof TrainingCertificationProfessionalCertificationsWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-certification/programmes/$slug': {
      id: '/training-certification/programmes/$slug'
      path: '/training-certification/programmes/$slug'
      fullPath: '/training-certification/programmes/$slug'
      preLoaderRoute: typeof TrainingCertificationProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CngRoute: CngRoute,
  ContactRoute: ContactRoute,
  EeaRoute: EeaRoute,
  EnergyEcommerceRoute: EnergyEcommerceRoute,
  EnergySavingEquipmentRoute: EnergySavingEquipmentRoute,
  EnergyTransitionRoute: EnergyTransitionRoute,
  EvRoute: EvRoute,
  FaqRoute: FaqRoute,
  GetElectricityRoute: GetElectricityRoute,
  GetFuelRoute: GetFuelRoute,
  GreenEnergyRoute: GreenEnergyRoute,
  IndustriesRoute: IndustriesRoute,
  InvestRoute: InvestRoute,
  LoginRoute: LoginRoute,
  OurServicesRoute: OurServicesRoute,
  PartnersRoute: PartnersRoute,
  PayBillsRoute: PayBillsRoute,
  PowerAsAServiceRoute: PowerAsAServiceRoute,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  RequestEnergyQuoteRoute: RequestEnergyQuoteRoute,
  SmartMeteringRoute: SmartMeteringRoute,
  SolarPowerRoute: SolarPowerRoute,
  TechnologyRoute: TechnologyRoute,
  TrainingRoute: TrainingRoute,
  ApiSophiaRoute: ApiSophiaRoute,
  CompanyAboutRoute: CompanyAboutRoute,
  CompanyCareersRoute: CompanyCareersRoute,
  CompanyContactRoute: CompanyContactRoute,
  CompanyFaqRoute: CompanyFaqRoute,
  CompanyGreenEnergyRoute: CompanyGreenEnergyRoute,
  CompanyIndustriesRoute: CompanyIndustriesRoute,
  CompanyPartnersRoute: CompanyPartnersRoute,
  CompanyTechnologyRoute: CompanyTechnologyRoute,
  PoliciesGenderDiversityInclusionRoute: PoliciesGenderDiversityInclusionRoute,
  SophiaThreadIdRoute: SophiaThreadIdRoute,
  TrainingCertificationCorporateRoute: TrainingCertificationCorporateRoute,
  TrainingCertificationCpdRoute: TrainingCertificationCpdRoute,
  TrainingCertificationVerifyRoute: TrainingCertificationVerifyRoute,
  TrainingCertificationWaitlistRoute: TrainingCertificationWaitlistRoute,
  SophiaIndexRoute: SophiaIndexRoute,
  TrainingCertificationIndexRoute: TrainingCertificationIndexRoute,
  CompanySolutionsCngRoute: CompanySolutionsCngRoute,
  CompanySolutionsCngConversionRoute: CompanySolutionsCngConversionRoute,
  CompanySolutionsDieselRoute: CompanySolutionsDieselRoute,
  CompanySolutionsEeaRoute: CompanySolutionsEeaRoute,
  CompanySolutionsElectricityRoute: CompanySolutionsElectricityRoute,
  CompanySolutionsEvChargingRoute: CompanySolutionsEvChargingRoute,
  CompanySolutionsEvMobilityRoute: CompanySolutionsEvMobilityRoute,
  CompanySolutionsMiniGridsRoute: CompanySolutionsMiniGridsRoute,
  CompanySolutionsPowerAsAServiceRoute: CompanySolutionsPowerAsAServiceRoute,
  CompanySolutionsRenewablesRoute: CompanySolutionsRenewablesRoute,
  CompanySolutionsSmartMeteringRoute: CompanySolutionsSmartMeteringRoute,
  CompanySolutionsTrainingRoute: CompanySolutionsTrainingRoute,
  TrainingCertificationProfessionalCertificationsCodeRoute:
    TrainingCertificationProfessionalCertificationsCodeRoute,
  TrainingCertificationProfessionalCertificationsWaitlistRoute:
    TrainingCertificationProfessionalCertificationsWaitlistRoute,
  TrainingCertificationProgrammesSlugRoute:
    TrainingCertificationProgrammesSlugRoute,
  CompanySolutionsIndexRoute: CompanySolutionsIndexRoute,
  TrainingCertificationProfessionalCertificationsIndexRoute:
    TrainingCertificationProfessionalCertificationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
